// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchoolETL.Data;

#nullable disable

namespace v3.Migrations
{
    [DbContext(typeof(DwContext))]
    partial class DwContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchoolETL.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FotoPath")
                        .HasColumnType("text")
                        .HasColumnName("foto_path");

                    b.Property<decimal?>("FrequenciaGeral")
                        .HasColumnType("numeric")
                        .HasColumnName("frequencia_geral");

                    b.Property<Guid?>("ImportId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_id");

                    b.Property<string>("Matricula")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("matricula");

                    b.Property<string>("Nome")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<string>("SituacaoCurso")
                        .HasColumnType("text")
                        .HasColumnName("situacao_curso");

                    b.HasKey("Id");

                    b.HasIndex("ImportId");

                    b.HasIndex("Matricula");

                    b.ToTable("alunos");
                });

            modelBuilder.Entity("SchoolETL.Models.AlunoObservacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer")
                        .HasColumnName("aluno_id");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em_utc");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("aluno_observacoes");
                });

            modelBuilder.Entity("SchoolETL.Models.Bimestre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("bimestres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "1º"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "2º"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "3º"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "4º"
                        });
                });

            modelBuilder.Entity("SchoolETL.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<Guid?>("ImportId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_id");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sigla");

                    b.HasKey("Id");

                    b.HasIndex("ImportId");

                    b.HasIndex("Sigla")
                        .IsUnique();

                    b.ToTable("cursos");
                });

            modelBuilder.Entity("SchoolETL.Models.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CargaHorariaRotulo")
                        .HasColumnType("text")
                        .HasColumnName("carga_horaria_rotulo");

                    b.Property<Guid?>("ImportId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_id");

                    b.Property<string>("NomeArea")
                        .HasColumnType("text")
                        .HasColumnName("nome_area");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sigla");

                    b.HasKey("Id");

                    b.HasIndex("ImportId");

                    b.HasIndex("Sigla")
                        .IsUnique();

                    b.ToTable("disciplinas");
                });

            modelBuilder.Entity("SchoolETL.Models.Etapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("etapas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Etapa 1"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Etapa 2"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Etapa 3"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Etapa 4"
                        },
                        new
                        {
                            Id = 99,
                            Nome = "Etapa Final"
                        });
                });

            modelBuilder.Entity("SchoolETL.Models.FatoNota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer")
                        .HasColumnName("aluno_id");

                    b.Property<int>("BimestreId")
                        .HasColumnType("integer")
                        .HasColumnName("bimestre_id");

                    b.Property<int?>("CursoId")
                        .HasColumnType("integer")
                        .HasColumnName("curso_id");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("integer")
                        .HasColumnName("disciplina_id");

                    b.Property<int>("EtapaId")
                        .HasColumnType("integer")
                        .HasColumnName("etapa_id");

                    b.Property<decimal?>("Frequencia")
                        .HasColumnType("numeric")
                        .HasColumnName("frequencia");

                    b.Property<Guid>("ImportId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_id");

                    b.Property<decimal?>("Nota")
                        .HasColumnType("numeric")
                        .HasColumnName("nota");

                    b.Property<int?>("PeriodoLetivoId")
                        .HasColumnType("integer")
                        .HasColumnName("periodo_letivo_id");

                    b.Property<int?>("SituacaoId")
                        .HasColumnType("integer")
                        .HasColumnName("situacao_id");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("BimestreId");

                    b.HasIndex("CursoId");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("EtapaId");

                    b.HasIndex("ImportId");

                    b.HasIndex("PeriodoLetivoId");

                    b.HasIndex("SituacaoId");

                    b.ToTable("fato_notas");
                });

            modelBuilder.Entity("SchoolETL.Models.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("FileName")
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<int?>("PeriodoLetivoId")
                        .HasColumnType("integer")
                        .HasColumnName("periodo_letivo_id");

                    b.HasKey("Id");

                    b.HasIndex("PeriodoLetivoId");

                    b.ToTable("imports");
                });

            modelBuilder.Entity("SchoolETL.Models.ImportSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid>("ImportId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ImportId", "Name")
                        .IsUnique();

                    b.ToTable("import_sheets");
                });

            modelBuilder.Entity("SchoolETL.Models.PeriodoLetivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("Semestre")
                        .HasColumnType("integer")
                        .HasColumnName("semestre");

                    b.HasKey("Id");

                    b.ToTable("periodos");
                });

            modelBuilder.Entity("SchoolETL.Models.Situacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.ToTable("situacoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "APR"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "REP"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "CAN"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "CUR"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "OUT"
                        });
                });

            modelBuilder.Entity("SchoolETL.Models.AlunoObservacao", b =>
                {
                    b.HasOne("SchoolETL.Models.Aluno", "Aluno")
                        .WithMany("Observacoes")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("SchoolETL.Models.FatoNota", b =>
                {
                    b.HasOne("SchoolETL.Models.Aluno", "Aluno")
                        .WithMany("Notas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolETL.Models.Bimestre", "Bimestre")
                        .WithMany("Notas")
                        .HasForeignKey("BimestreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolETL.Models.Curso", "Curso")
                        .WithMany("Notas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchoolETL.Models.Disciplina", "Disciplina")
                        .WithMany("Notas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolETL.Models.Etapa", "Etapa")
                        .WithMany("Notas")
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolETL.Models.PeriodoLetivo", "PeriodoLetivo")
                        .WithMany("Notas")
                        .HasForeignKey("PeriodoLetivoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchoolETL.Models.Situacao", "Situacao")
                        .WithMany("Notas")
                        .HasForeignKey("SituacaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Aluno");

                    b.Navigation("Bimestre");

                    b.Navigation("Curso");

                    b.Navigation("Disciplina");

                    b.Navigation("Etapa");

                    b.Navigation("PeriodoLetivo");

                    b.Navigation("Situacao");
                });

            modelBuilder.Entity("SchoolETL.Models.ImportBatch", b =>
                {
                    b.HasOne("SchoolETL.Models.PeriodoLetivo", "PeriodoLetivo")
                        .WithMany()
                        .HasForeignKey("PeriodoLetivoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PeriodoLetivo");
                });

            modelBuilder.Entity("SchoolETL.Models.ImportSheet", b =>
                {
                    b.HasOne("SchoolETL.Models.ImportBatch", "ImportBatch")
                        .WithMany("Sheets")
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("SchoolETL.Models.Aluno", b =>
                {
                    b.Navigation("Notas");

                    b.Navigation("Observacoes");
                });

            modelBuilder.Entity("SchoolETL.Models.Bimestre", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("SchoolETL.Models.Curso", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("SchoolETL.Models.Disciplina", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("SchoolETL.Models.Etapa", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("SchoolETL.Models.ImportBatch", b =>
                {
                    b.Navigation("Sheets");
                });

            modelBuilder.Entity("SchoolETL.Models.PeriodoLetivo", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("SchoolETL.Models.Situacao", b =>
                {
                    b.Navigation("Notas");
                });
#pragma warning restore 612, 618
        }
    }
}
